config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :articles 

  #BOOKMARKS
  put '/article/:id/bookmark', to: 'articles#bookmark', as: 'bookmark'
  delete '/article/:id/bookmark', to: 'articles#delete_bookmark', as: 'remove_bookmark'
  get '/users/bookmarks', to: 'articles#find_bookmarks', as: 'bookmarks'

  #LIKES
  put '/article/:id/likes', to: 'articles#like', as: 'like'
  delete '/article/:id/likes', to: 'articles#delete_like', as: 'remove_like'
  get '/users/likes', to: 'articles#find_likes', as: 'likes'

  #FOLLOWS
  post '/users/:id/follow', to: "users#follow", as: "follow"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  get '/users/:id/followers', to: "users#followers", as: "follower"
  get '/users/:id/following', to: "users#followees", as: "followee"
  # post '/articles/:id/follow', to: "users#follow_by_article", as: "follow_by_article"
  # delete '/articles/:id/unfollow', to: "users#unfollow_by_article", as: "unfollow_by_article"
  get '/users/following', to: 'users#following', as: 'following'
  get '/users/followers', to: 'users#followers', as: 'followers'
  
  namespace :api, defaults: { format: :json } do
     namespace :v1 do
       post 'authenticate', to: 'authentication#authenticate'
       resources :articles, only: [:index]
     end
   end
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :registrations => 'users/registrations' }
  resources :users, :only => [:show]

  
  root to: "articles#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :bookmarks
  has_many :likes
  has_one_attached :photo
  has_rich_text :content

  # acts_as_commontable dependent: :destroy
  validates :photo, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 0..4.megabytes }, :on => :create
  validates :photo, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 0..4.megabytes }, :on => :update
  validates_length_of :title, minimum: 5, maximum: 40

  def bookmarked?(user)
    !!self.bookmarks.find{|bookmark| bookmark.user_id == user.id}
  end

  def liked?(user)
    !!self.likes.find{|like| like.user_id == user.id}
  end

  validates :title, presence: true
  validates :content, presence: true

  def self.posted
    where('scheduled_for < ? OR scheduled_for IS NULL', DateTime.now)
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::ApplicationController
  def index
    @articles = Article.all
    render json: @articles.to_json, status: :ok
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    # commontator_thread_show(@article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update

    @article.user = current_user

    if article_params["photo"]
      @article.photo.purge
      @article.photo.attach(article_params["photo"])
    end
    
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bookmark
    @article = Article.find(params[:id])
    Bookmark.create(user_id: current_user.id, article_id: @article.id)
    redirect_to article_path(@article)
  end

  def delete_bookmark
    @article = Article.find(params[:id])
    @article.bookmarks.where(user: current_user).destroy_all
    redirect_to article_path(@article)
  end

  def find_bookmarks
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end

  def like
    @article = Article.find(params[:id])
    Like.create(user_id: current_user.id, article_id: @article.id)
    redirect_to article_path(@article)
  end

  def delete_like
    @article = Article.find(params[:id])
    @article.likes.where(user: current_user).destroy_all
    redirect_to article_path(@article)
  end

  def find_likes
    @likes = Like.where(user_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :thumbnail_url, :photo)
    end

    def authorize_user!
      redirect_back fallback_location: root_path, alert: 'Nimate dostopa do te strani.' unless current_user == @article.user || current_user.admin?
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  require "mini_magick"

    def resized_image(image)
      image = MiniMagick::Image.open(image)
      image.resize "400x400"
      image.rotate "-90"
    end
  
    def display_index_article_links(article)
      capture do
        concat link_to('Preberi več', article, class: 'stretched-link')
      end
    end

    def display_show_article_links(article)
    capture do
      if current_user == article.user
        concat link_to 'Izbriši', article, method: :delete, data: { confirm: 'Are you sure?' }
        concat ' | '
        concat link_to 'Uredi', edit_article_path(article)
        concat ' | '
      end
      concat link_to 'Back', articles_path
    end
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
<% if article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

  <ul>
    <% article.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group mb-2">
  <%= form.label :title %>
  <%= form.text_field :title, class:"form-control", required: true %>
</div>

<div class="form-group mb-2">
  <%= form.label :content %>
  <%= form.rich_text_area :content, required: true %>
</div>
<% if article.photo.attached? %>
<h4 class="mt-4">Thumbnail:</h4>
<%= image_tag(article.photo, style:"width: 200px; height: 200px; display: block;") if article.photo.attached? %>
<% end %>
<div class="input-group my-3">

  <div class="custom-file">
    <%= form.file_field :photo, class: "custom-file-input" %>
    <label class="custom-file-label" for="image">Upload thumbnail</label>
  </div>
</div>

<div class="actions mb-2">
  <%= form.submit class:"btn btn-primary" %>
</div>
<% end %>

<script>
  // Add the following code if you want the name of the file appear on select
  $(".custom-file-input").on("change", function () {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });
</script>

app/views/articles/edit.html.erb
<h1 class="my-4 title">Update Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/find_bookmarks.html.erb
<div>
    <h1 class="title mb-4">Your Bookmarks</h1>
    <% if @bookmarks.empty? %>
        <span class="d-block" style="font-size: 20px;">No bookmarks were found..</span>
    <% else %> 
    <div class="row my-2">
        <% @bookmarks.each do |bookmark| %>
        <% article = Article.find_by(id: bookmark.article_id) %>
        <div class="col-md-6">
            <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                    <h3 class="mb-0">
                        <%= link_to article, class:"text-dark title" do %>
                        <%= article.title %>
                        <% end %>
                    </h3>
                    <div class="mb-1 text-muted"><%= article.created_at.strftime('%b %d, %Y') %> </div>
                    <p class="card-text mb-auto">
                        <%= truncate(strip_tags(article.content.to_s), length: 120) %>
                    </p>
                    <p class="lead mb-0">
                        <%= link_to "Continue reading..", article, class:"text-dark font-weight-bold" %></p>
                </div>
                <%= link_to article_path(article.id) do %>
                <%= image_tag(article.photo, class:"card-img-right flex-auto d-none d-lg-block", style:"height: 200px; width: 250px;") if article.photo.attached? %>
                <% end %>
            </div>
        </div>
        <% end %>
    </div>
    <% end %> 
</div>

app/views/articles/index.html.erb
<div class="row" id="all-articles">
  <% if @articles.blank? %>
  <span style="font-size: 20px;">No articles were found..</span>
  <% else %>
  <% @articles.each do |article| %>
  <% if article.ultra_featured? %>
  <div class="col-12">
    <div class="jumbotron p-3 p-md-5 text-white rounded featured-background">
      <div class="col-md-6 px-0">
        <h1 class="display-4 font-italic title"><%= article.title %></h1>
        <p class="lead my-3"><%= truncate(strip_tags(article.content.to_s), length: 60) %></p>
        <p class="lead mb-0"><%= link_to "Continue reading..", article, class:"text-white font-weight-bold" %></p>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>

  <% @articles.each do |article| %>
  <% if article.featured? %>
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0">
          <%= link_to article, class:"text-dark title" do %>
          <%= article.title %>
          <% end %>
        </h3>
        <div class="mb-1 text-muted"><%= article.created_at.strftime('%b %d, %Y') %> </div>
        <p class="card-text mb-auto">
          <%= truncate(strip_tags(article.content.to_s), length: 100) %>
        </p>
        <p class="lead mb-0"><%= link_to "Continue reading..", article, class:"text-dark font-weight-bold" %></p>
      </div>
      <%= link_to article_path(article.id) do %>
      <%= image_tag(article.photo, class:"card-img-right flex-auto d-none d-lg-block", style:"height: 200px; width: 250px;") if article.photo.attached? %>
      <% end %>
    </div>
  </div>
  <% end %>
  <% end %>

  <% @articles.each do |article| %>

  <% if !article.featured && !article.ultra_featured %>
  <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6 col-12  my-2">
    <div class="card">
      <%= link_to article_path(article.id) do %>
      <%= image_tag(article.photo, class:"card-img-top", style:"max-height: 150px;") if article.photo.attached? %>
      <% end %>
      <div class="card-body">

        <%= link_to user_path(article.user) do  %>
        <% if article.user.photo.attached? %>
        <%= image_tag(article.user.photo, class:"profile-image") if article.user.photo.attached? %>
        <% elsif article.user.icon_url %>
        <%= image_tag(article.user.icon_url, class: "profile-image") %>
        <% else %>
        <%= image_tag('placeholder-image.jpg', class:"profile-image") %>
        <% end %>

        <strong class="p-2 author-name"> <%= article.user.name || 'Neznan avtor' %> </strong>
        <% end %>

        <%= link_to article_path(article.id) do %>
        <h5 class="text-dark title mt-3 mb-2"> <%= article.title %> </h5>
        <% end %> 
        <p class="my-2 card-text"><%= truncate(strip_tags(article.content.to_s), length: 50) %></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated <%= time_ago_in_words(article.updated_at) %> ago</small>
      </div>
    </div>
  </div>
  <% end %>

  <% end %>
  <% end %>
</div>

<a href="<%= new_article_path %>" class="btn btn-article btn-primary my-2">New Article <%= fa_icon "plus" %></a>
<!-- <%= link_to 'New Article', new_article_path, class:"btn btn-article btn-primary my-2" %> -->

app/views/articles/new.html.erb
<h1 class="my-4 title">New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row justify-content-center my-4" id="single-article">
  <div class="col-12 col-xl-6 col-lg-8 ">
    <div>
      <h2 class="title my-2"> <%=@article.title%> </h2>

      <div class="my-4 row justify-content-between align-items-center">
        <div class="col-9">
          <%= link_to user_path(@article.user) do  %>
          <% if @article.user.photo.attached? %>
          <%= image_tag(@article.user.photo, class:"profile-image") if @article.user.photo.attached? %>
          <% elsif @article.user.icon_url %>
          <%= image_tag(@article.user.icon_url, class: "profile-image") %>
          <% else %>
          <%= image_tag('placeholder-image.jpg', class:"profile-image") %>
          <% end %>

          <strong class="p-2 author-name"> <%= @article.user.name || 'Neznan avtor' %> </strong>
          <% end %> 
        </div>
        <div class="col-3 d-flex justify-content-end align-items-center">
          <% if current_user %>
            <% if current_user.id == @article.user.id || current_user.admin? %>
              <% if current_user.id == @article.user.id %>
              <%= link_to  edit_article_path(@article), class: 'mb-3 ml-2' do %>
                <i class="far fa-pen article-icon"></i>
              <% end %>
              <% end %> 
              <%= link_to @article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'mb-3 ml-2' do %>
                <i class="fas fa-trash-alt article-icon text-danger ml-2"></i>
              <% end %>
            <% elsif current_user.id != @article.user.id %>
              <% if @article.bookmarked?(current_user) %>
                <%= link_to remove_bookmark_path(@article), class: "mx-2", method: "delete" do %>
                  <i class="fas fa-bookmark article-icon"></i>
                <% end %>
              <% else %>
                <%= link_to bookmark_path(@article), class: "mx-2", method: "put" do %>
                  <i class="far fa-bookmark article-icon"></i>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <%= image_tag(@article.photo, class:"article-image") if @article.photo.attached? %>
    <p class="my-2"><%= @article.content %></p>
    <% if user_signed_in? %>
    <% if @article.liked?(current_user) %>
    <%= link_to remove_like_path(@article), class: "mx-2", method: "delete" do %>
    <i class="fas fa-heart article-icon"></i>
    <% end %>
    <% else %>
    <%= link_to like_path(@article),  class: "mx-2", method: "put" do%>
    <i class="far fa-heart article-icon"></i>
    <% end %>

    
    <% end %>
    <span class="title"><%= @article.likes.count %> <%= (@article.likes.count) == 1 ? 'Like' : 'Likes'%></span>

    <% end %>

    <!-- <%= display_show_article_links(@article) %> -->
  </div>
</div>