config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :articles 

  #BOOKMARKS
  put '/article/:id/bookmark', to: 'articles#bookmark', as: 'bookmark'
  delete '/article/:id/bookmark', to: 'articles#delete_bookmark', as: 'remove_bookmark'
  get '/users/bookmarks', to: 'articles#find_bookmarks', as: 'bookmarks'

  #LIKES
  put '/article/:id/likes', to: 'articles#like', as: 'like'
  delete '/article/:id/likes', to: 'articles#delete_like', as: 'remove_like'
  get '/users/likes', to: 'articles#find_likes', as: 'likes'

  #FOLLOWS
  post '/users/:id/follow', to: "users#follow", as: "follow"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  get '/users/:id/followers', to: "users#followers", as: "follower"
  get '/users/:id/following', to: "users#followees", as: "followee"
  # post '/articles/:id/follow', to: "users#follow_by_article", as: "follow_by_article"
  # delete '/articles/:id/unfollow', to: "users#unfollow_by_article", as: "unfollow_by_article"
  get '/users/following', to: 'users#following', as: 'following'
  get '/users/followers', to: 'users#followers', as: 'followers'
  
  namespace :api, defaults: { format: :json } do
     namespace :v1 do
       post 'authenticate', to: 'authentication#authenticate'
       resources :articles, only: [:index]
     end
   end
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :registrations => 'users/registrations' }
  resources :users, :only => [:show]

  
  root to: "articles#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable,
  :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :articles, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :photo

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users


  # acts_as_commontator
  
  validates :photo, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 0..3.megabytes }

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
    if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    if(auth.info.email?)
        user.email = auth.info.email
    else
        user.email = "test@test.com"
    end
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.icon_url = auth.info.image
  end
end

# def following?(user)
#   !!self.followings.find{|follow| follow.user_id == user.id}
# end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      Rails.logger.info(@user.errors.full_messages)
      session["devise.facebook_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to root_path, alert: "Authentication error. User with this email already exists!"
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      Rails.logger.info(@user.errors.full_messages)
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to root_path, alert: "Authentication error. User with this email already exists!"
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    # Require current password if user is trying to change password.
    if !current_user.provider
    return super if params["password"]&.present?
    end
    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!

    def show
        @user = User.find_by_id(params[:id])
        @articles = Article.all.where(user: params[:id])
    end
    def update_password
      @user = current_user
      if @user.update(user_params)
        # Sign in the user by passing validation in case their password changed
        bypass_sign_in(@user)
        redirect_to root_path
      else
        render "edit"
      end
    end

    # def follow_by_article
    #   @article = Article.find(params[:id])
    #   Follow.create(follower_id: current_user.id, followed_id: @article.user.id)
    #   redirect_to article_path(@article)
    # end

    # def unfollow_by_article
    #   @article = Article.find(params[:id])
    #   current_user.followings.find_by(followed_id: @article.user.id).destroy
    #   redirect_to article_path(@article)
    # end

def follow
  @user = User.find(params[:id])
  current_user.followees << @user
  redirect_back(fallback_location: user_path(@user))
end

def unfollow
  @user = User.find(params[:id])
  current_user.followed_users.find_by(followee_id: @user.id).destroy
  redirect_back(fallback_location: user_path(@user))
end

def followers
  @user = User.find(params[:id])
  @followers = @user.followers
end

def followees
  @user = User.find(params[:id])
  @followees = @user.followees
end

    private
  
    def user_params
      # NOTE: Using `strong_parameters` gem
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followees.html.erb
<div class="row" id="user-profile">
    <div class="col-12">
        <div class="row justify-content-between">
            <div class="col-12">
                <span class="title my-2 d-block-inline">
                    <%= link_to user_path(@user) do  %>
                    <% if @user.photo.attached? %>
                    <%= image_tag(@user.photo, class:"profile-image") if @user.photo.attached? %>
                    <% elsif @user.icon_url %>
                    <%= image_tag(@user.icon_url, class: "profile-image") %>
                    <% else %>
                    <%= image_tag('placeholder-image.jpg', class:"profile-image") %>
                    <% end %>
                    <% end %>
                    <%= link_to user_path(@user) do  %>
                    <span class="mx-2 title user-profile text-dark">
                        <%= @user.name %>
                    </span>
                    <% end %>
                    <% if current_user.id != @user.id %>
                    <% if current_user.followees.include?(@user) %>
                    <%= link_to "Unfollow", unfollow_path, class: "btn btn-dark d-block-inline mb-2", method: "POST" %>
                    <% else %>
                    <%= link_to "Follow", follow_path, class: "btn btn-dark d-block-inline mb-2", method: "POST"  %>
                    <% end%>
                    <% end %>
                </span>
            </div>

        </div>
        <div>
            <span class="my-4 d-block title article-title" style="font-size: 20px;">
                <%= @user.followees.count %>
                <%= link_to "Following", followee_path(@user), class:"d-block-inline mr-2", style:"color: black;" %>
                <%= @user.followers.count %>
                <%= link_to "Followers", follower_path(@user), class:"d-block-inline", style:"color: black;"  %>
            </span>
        </div>
        <div class="my-5">
            <span class="title my-3 d-block" style="font-size: 29px;">
                Following
            </span>
            <% if @followees.blank? %>
            <span style="font-size: 20px;">No followees were found..</span>
            <% else %>

            <% @followees.each do |followee| %>
            <div class="col-12 my-2">

                <span class="title my-2 d-block">
                    <%= link_to user_path(followee) do %>
                    <% if followee.photo.attached? %>
                    <%= image_tag(followee.photo, class:"profile-image follow-image") if followee.photo.attached? %>
                    <% elsif followee.icon_url %>
                    <%= image_tag(followee.icon_url, class: "profile-image follow-image") %>
                    <% else %>
                    <%= image_tag('placeholder-image.jpg', class:"profile-image follow-image") %>
                    <% end %>
                    <span class="mx-2 text-dark">
                        <%= followee.name %>
                    </span>
                    <% end %>
                    <% if current_user.id != followee.id %>
                    <% if current_user.followees.include?(followee) %>
                    <%= link_to "Unfollow", unfollow_path(followee.id), class: "btn btn-dark d-block-inline", method: "POST" %>
                    <% else %>
                    <%= link_to "Follow", follow_path(followee.id), class: "btn btn-dark d-block-inline", method: "POST"  %>
                    <% end %>
                    <% end %>

                </span>
                <span class="d-block">
                    <%= followee.bio || "Hi! My name is #{followee.name}!" %>
                </span>
                <hr class="follow-divider">

            </div>
            <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/followers.html.erb
<div class="row" id="user-profile">
    <div class="col-12">
        <div class="row justify-content-between">
            <div class="col-12">
                <span class="title my-2 d-block-inline">
                    <%= link_to user_path(@user) do  %>
                    <% if @user.photo.attached? %>
                    <%= image_tag(@user.photo, class:"profile-image") if @user.photo.attached? %>
                    <% elsif @user.icon_url %>
                    <%= image_tag(@user.icon_url, class: "profile-image") %>
                    <% else %>
                    <%= image_tag('placeholder-image.jpg', class:"profile-image") %>
                    <% end %>
                    <% end %>
                    <%= link_to user_path(@user) do  %>
                    <span class="mx-2 title user-profile text-dark">
                        <%= @user.name %>
                    </span>
                    <% end %>
                    <% if current_user.id != @user.id %>
                    <% if current_user.followees.include?(@user) %>
                    <%= link_to "Unfollow", unfollow_path, class: "btn btn-dark d-block-inline mb-2", method: "POST" %>
                    <% else %>
                    <%= link_to "Follow", follow_path, class: "btn btn-dark d-block-inline mb-2", method: "POST"  %>
                    <% end%>
                    <% end %>
                </span>
            </div>

        </div>
        <div>
            <span class="my-4 d-block title article-title" style="font-size: 20px;">
                <%= @user.followees.count %>
                <%= link_to "Following", followee_path(@user), class:"d-block-inline mr-2", style:"color: black;" %>
                <%= @user.followers.count %>
                <%= link_to "Followers", follower_path(@user), class:"d-block-inline", style:"color: black;"  %>
            </span>
        </div>
        <div class="my-5">
            <span class="title my-3 d-block" style="font-size: 29px;">
                Followers
            </span>
            <% if @followers.blank? %>
            <span style="font-size: 20px;">No followers were found..</span>
            <% else %>

            <% @followers.each do |follower| %>
            <div class="col-12 my-2">

                <span class="title my-2 d-block">
                    <%= link_to user_path(follower) do %>
                    <% if follower.photo.attached? %>
                    <%= image_tag(follower.photo, class:"profile-image follow-image") if follower.photo.attached? %>
                    <% elsif follower.icon_url %>
                    <%= image_tag(follower.icon_url, class: "profile-image follow-image") %>
                    <% else %>
                    <%= image_tag('placeholder-image.jpg', class:"profile-image follow-image") %>
                    <% end %>
                    <span class="mx-2 text-dark">
                        <%= follower.name %>
                    </span>
                    <% end %>
                    <% if current_user.id != follower.id %>
                    <% if current_user.followees.include?(follower) %>
                    <%= link_to "Unfollow", unfollow_path(follower.id), class: "btn btn-dark d-block-inline", method: "POST" %>
                    <% else %>
                    <%= link_to "Follow", follow_path(follower.id), class: "btn btn-dark d-block-inline", method: "POST"  %>
                    <% end %>
                    <% end %>
                </span>
                <span class="d-block">
                    <%= follower.bio || "Hi! My name is #{follower.name}!" %>
                </span>
                <hr class="follow-divider">

            </div>
            <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="row" id="user-profile">
    <div class="col-12">
        <div class="row justify-content-between">
            <div class="col-9">
                <span class="title my-2 d-block-inline">
                    <% if @user.photo.attached? %>
                    <%= image_tag(@user.photo, class:"profile-image") if @user.photo.attached? %>
                    <% elsif @user.icon_url %>
                    <%= image_tag(@user.icon_url, class: "profile-image") %>
                    <% else %>
                    <%= image_tag('placeholder-image.jpg', class:"profile-image") %>
                    <% end %>
                    <span class="mx-2">
                        <%= @user.name %>
                    </span>
                    <% if current_user.id != @user.id %>
                    <% if current_user.followees.include?(@user) %>
                    <%= link_to "Unfollow", unfollow_path, class: "btn btn-dark d-block-inline mb-2", method: "POST" %>
                    <% else %>
                    <%= link_to "Follow", follow_path, class: "btn btn-dark d-block-inline mb-2", method: "POST"  %>
                    <% end%>
                    <% end %>
                </span>
            </div>
            <div class="col-3 d-flex align-items-center justify-content-end">
                <% if current_user %>
                <% if current_user.id == @user.id %>
                <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary mb-3 ml-2' %>
                <% end %>
                <% end %>
            </div>
        </div>
        <div>
            <span class="my-4 d-block title article-title" style="font-size: 20px;">
                <%= @user.followees.count %>
                <%= link_to "Following", followee_path(@user), class:"d-block-inline mr-2", style:"color: black;" %>
                <%= @user.followers.count %>
                <%= link_to "Followers", follower_path(@user), class:"d-block-inline", style:"color: black;"  %>
            </span>
        </div>
        <div>
            <span class="subtitle mt-4">
                ABOUT
            </span>
            <span class="user-bio mt-2">
                <%= @user.bio || "Hi! My name is #{@user.name}!" %>
            </span>
        </div>
        <div class="my-5">
            <span class="title my-3 d-block" style="font-size: 29px;">
                My Articles
            </span>
            <% if @articles.empty? %>
            <span style="font-size: 20px;">
                No articles were found at the moment..
            </span>
            <% else %>
            <div class="row my-3">

                <% @articles.each do |article| %>

                <div class="col-12 col-xl-6 col-lg-6 my-2">
                    <%= link_to article_path(article.id) do %>
                    <small class="text-muted"><%= article.created_at.strftime('%b %d, %Y') %></small>
                    <span class="d-block mb-3 mt-1 title article-title"> <%= article.title %> </span>
                    <%= image_tag(article.photo, class:"article-photo") if article.photo.attached? %>
                    <% end %>

                    <p class="my-2"><%= truncate(strip_tags(article.content.to_s), length: 250) %></p>
                    <%= link_to article_path(article.id) do %>
                    <span class="text-dark" style="font-size: 16px;">Read more ~
                        <%= show_read_time(article.content.to_s) %> min read</span>
                    <% end %>
                </div>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
</div>