config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :articles 

  #BOOKMARKS
  put '/article/:id/bookmark', to: 'articles#bookmark', as: 'bookmark'
  delete '/article/:id/bookmark', to: 'articles#delete_bookmark', as: 'remove_bookmark'
  get '/users/bookmarks', to: 'articles#find_bookmarks', as: 'bookmarks'

  #LIKES
  put '/article/:id/likes', to: 'articles#like', as: 'like'
  delete '/article/:id/likes', to: 'articles#delete_like', as: 'remove_like'
  get '/users/likes', to: 'articles#find_likes', as: 'likes'

  #FOLLOWS
  post '/users/:id/follow', to: "users#follow", as: "follow"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  get '/users/:id/followers', to: "users#followers", as: "follower"
  get '/users/:id/following', to: "users#followees", as: "followee"
  # post '/articles/:id/follow', to: "users#follow_by_article", as: "follow_by_article"
  # delete '/articles/:id/unfollow', to: "users#unfollow_by_article", as: "unfollow_by_article"
  get '/users/following', to: 'users#following', as: 'following'
  get '/users/followers', to: 'users#followers', as: 'followers'
  
  namespace :api, defaults: { format: :json } do
     namespace :v1 do
       post 'authenticate', to: 'authentication#authenticate'
       resources :articles, only: [:index]
     end
   end
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :registrations => 'users/registrations' }
  resources :users, :only => [:show]

  
  root to: "articles#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Medirails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- This refers to app/javascript/stylesheets/application.scss-->
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>

<body>
  <div class="container content">
    <header class="blog-header py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-xl-8 col-lg-8 col-4 pt-1">
          <%= link_to root_path, class: 'blog-header-logo nav-logo text-dark' do %>
          <%= image_tag "medirails-logo.svg", :size => "150x50", :style => "display:inline-block;" %>
          <!-- <h2 class="nav-logo">Medi<span class="nav-logo-rails">rails</span> 
          </h2> -->
          <% end %>
          <span class="nav-greeting d-xl-inline-block d-none">
            <span style="color:rgb(201, 201, 201)" class="px-2">|</span><span class="greeting-text"
              style="font-weight: bold;"><%= get_time_of_day(Time.now.hour) %></span>
          </span>
        </div>
        <div class="col-8 col-xl-4 col-lg-4 d-flex justify-content-end align-items-center">
          <% if user_signed_in? %>
          <div class="btn-group">
            <a href="<%= bookmarks_path %>" class="my-2 btn">
              <i class="fal fa-bookmark mx-2 nav-icon"></i>
            </a>
            <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user fa-2x"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <h6 class="dropdown-header"><%= current_user.name %> </h6>
              <li>
                <%= link_to 'New Article', new_article_path, class:"dropdown-item" %>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Profile", user_path(current_user), class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to "Settings", edit_user_registration_path, class: 'dropdown-item' %>
              </li>
              <% if current_user.admin? %>
              <li>
                <%= link_to "Admin panel", rails_admin.dashboard_path, class: 'dropdown-item' %>
              </li>
              <% end %>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', :method => :delete %>
              </li>
            </div>
          </div>

          <% else %>
          <%= display_session_links %>
          <% end %>
        </div>
      </div>
    </header>
    <div class="my-5">
      <div class="row justify-content-center align-content-center">
        <div class="col-12">
          <% if notice %>
          <div class="alert alert-success" role="alert">
            <span class="d-block text-center"><%= notice %></span>
          </div>
          <% end %>
          <% if alert %>
          <div class="alert alert-warning" role="alert">
            <span class="d-block text-center"><%= alert %></span>
          </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </div>
</body>

<footer class="footer bg-light">
  <div class="row justify-content-center align-content-center">
    <div class="col-12 text-center align-content-center">
      <p style="font-size: 18px; vertical-align: middle;" class="my-4">Medirails built with <i class="fa fa-heart"
          style="color:red;"></i> by <a href="https://github.com/MatijaOsojnik">Matija </a>
      </p>
    </div>
  </div>
</footer>

</html>